### ISSUE TITLE
Add video header support

### ISSUE THREAD

**Issue by Pikamander2** [brainstormforce/astra#139]
Is there an easy way to use a video as the background of the header? I want a video to appear behind the nav links. It seems like WordPress [added support for it recently](https://make.wordpress.org/core/2016/11/26/video-headers-in-4-7/) but it doesn't seem like this theme supports it.

**Comment by Nikschavan** [comment]
Hey @Pikamander2,

Instead of adding support for video headers we have just released a separate addon `Advanced headers` as a part of [Astra Pro](https://wpastra.com/pro/). Advanced Header allows much more control over headers than just header background/ header Video and all that allows us to manage those options much more intuitively on a single screen.

As of yet the Advanced Headers also does not have this particular option to add video backgrounds but that will be added very soon in the next update to [Astra Pro](https://wpastra.com/pro/).

I would suggest you join our [Facebook group](https://www.facebook.com/groups/227391647730107/) if you have not so that you can stay connected with the latest announcements.
