### ISSUE TITLE
add_theme_support( 'editor-styles' );

### ISSUE THREAD

**Issue by laurentdebricon** [brainstormforce/astra#2167]
### Describe the bug:
Astra is not compatible with 
`add_theme_support( 'editor-styles' );
`
### Screenshots:
![Captura de tela de 2020-12-25 11-51-38](https://user-images.githubusercontent.com/736104/103133051-85e8ab00-46a8-11eb-9b94-e51d170afc2b.png)

**Comment by sparkthree** [comment]
I've experienced this as well and, from what I've seen, it's that once `add_theme_support( 'editor-styles' );` is called, Astra's handling of styles within the admin view override the WordPress default and cannot be fixed via styles in a custom stylesheet (since the styles called within an editor-styles stylesheet are limited in their scope.

For me, this was experienced in viewing the LazyBlocks (https://lazyblocks.com/) admin editing interface with `add_theme_support( 'editor-styles' );` added to my Astra child theme.

Here is the way it should be displayed (an example screenshot without editor-styles called):

![screenshot_LazyBlocksUI_No-Editor-Styles](https://user-images.githubusercontent.com/18536255/149827649-ef933fa3-1164-4e24-982c-1044550da487.png)

Here is how it displays when editor-styles are called via the child theme's functions.php:

![screenshot_LazyBlocksUI_With-Editor-Styles](https://user-images.githubusercontent.com/18536255/149827746-b55065b4-82ad-4be5-a151-d397b0594e1e.png)

**Comment by thebengalboy** [comment]
We are aware of this and plan to introduce it with the FSE update. Closing this issue because FSE-related tasks are now managed in a different location.
