### ISSUE TITLE
Lower css specificity

### ISSUE THREAD

**Issue by kimmenbert** [brainstormforce/astra#3893]
Hi,

We try writing as clean css as possible, and this is always a bit "ruined" by parent themes / third party plugins etc.

I wish you could write your css less specific if possible. In the example below, you are by default removing the WooCommerce css, so there shouldn't really be any other plugins etc. that would override your css.

For this example, `.woocommerce-tabs` is unique, shouldn't be a need for `.woocommerce div.product`
`.woocommerce-tabs li.active::before` is really all that should be needed, but `.woocommerce-tabs ul.tabs li.active::before` is also ok.

https://github.com/brainstormforce/astra/blob/b1f98d0db4f187bb6a2d0b520a14f33fe6ea9d8b/assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css#L967

Another example could be: `.woocommerce div.product.ast-woo-product-no-review #reviews #respond p.comment-form-author` this could probably be shortened to `#respond p.comment-form-author`

I know this is quite the task to have done, but I just had to put it out there :)

**Comment by imnavanath** [comment]
Hi [kimmenbert](https://github.com/kimmenbert),

Thanks for reaching out to us.

We have added a task for this in our To-Do list this will be part of our future update. 

Best regards,

**Comment by nathanrodrigues2111** [comment]
Hi @kimmenbert 

Regarding this optimization, I have checked it and while optimization it does break our woocommerce styling due to css specificity change in some places and as its a breaking change this will kept on hold for now . But dont worry as mentioned by @imnavanath we have already added it in todo to release this optimization in a future update.
