### ISSUE TITLE
Astra Pro LifterLMS Options not Displaying

### ISSUE THREAD

**Issue by chrisbadgett** [brainstormforce/astra#433]
I have Astra Pro installed, but can't get the LifterLMS distraction free checkout or display account tabs vertically to show up.

URL: https://astratest2.wpengine.com/wp-admin/
USER: astra
PASS: 4rVa9Pi36z2f24gYEVu8wTyT

<img width="641" alt="customize__astra_lifterlms_test_ _lifterlms_loves_astra" src="https://user-images.githubusercontent.com/12163552/35767058-68cbcf2a-08b2-11e8-9a7b-bd17a68b6588.png">

<img width="783" alt="plugins_ _astra_lifterlms_test_ _wordpress" src="https://user-images.githubusercontent.com/12163552/35767062-717044d0-08b2-11e8-940c-6b6bee58782e.png">

**Comment by dineshchouhan** [comment]
@chrisbadgett, I have checked your site and found that folder name of theme is `astra-lifterlms` instead of `astra`. Can you please check and rename it will `astra`.

**Comment by sujaypawar** [comment]
Hello @chrisbadgett — I went ahead and installed the correct version of Astra on your website. Now you should be able to see all Astra Pro options for LifterLMS.

Would you mind taking a look again and offer any other feedback you might have?

**Comment by Nikschavan** [comment]
This issue is because Astra Pro does not load any of its classes if the theme is not Astra. This is checked by checking [get_template()](https://developer.wordpress.org/reference/functions/get_template/) and if the directory name is changed `get_template()` does not return correct output hence Astra Pro does not load itself.

Also changing the directory name is not recommended as that will stop receiving the theme updates from W.org so we will keep the condition as is for now.

I will close this issue off @chrisbadgett. If you do notice any more issues regarding the compatibility do let us know!
