### ISSUE TITLE
Quantity plus/minus buttons change event not working on AJAX add to cart buttons

### ISSUE THREAD

**Issue by SuperHanss** [brainstormforce/astra#5139]
### Describe the bug:
#5106 introduced a change event for the quantity buttons however it is not working correctly on AJAX add to cart buttons on the shop page.

https://github.com/brainstormforce/astra/blob/5e6c7155cc3fb71ea62fae3f03d0f95b60ec9a94/assets/js/unminified/add-to-cart-quantity-btn.js#L179

Enabling bubbling fixes the issue:
`var changeEvent = new Event('change', { bubbles: true });`

### To reproduce:
1. Enable the quantity input field on the shop page of your Woocommerce store using _Quantity Field on Shop Page for WooCommerce_ plugin as an example.
2. Enable Astra quantity plus and minus buttons.
3. Use the '+' button to add more than one item the cart.
4. Note that only one item is being added to the cart.

### Expected behavior:
Correct quantity should be added to cart.

### Screenshots:
[](https://github.com/brainstormforce/astra/assets/6452565/17c7f24f-76aa-4e0b-928a-b1f7d15c42c3)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2

### Astra Theme version:
4.1.4

**Comment by SuperHanss** [comment]
@yssambare12 are you guys able to reproduce this?

**Comment by yssambare12** [comment]
Hi @SuperHanss ,

Thank you for bringing the issue with the Quantity Field on the Shop Page plugin to our attention. We appreciate your suggestion, and we wanted to let you know that we have implemented the changes you recommended after thoroughly testing them. Fix PR - https://github.com/brainstormforce/astra/pull/5184

During our testing process, we encountered various scenarios to ensure the effectiveness of the solution. As a result, it took some time to address the issue. We apologize for any inconvenience this may have caused you.

Additionally, we would like to confirm that the problem you encountered was not directly caused by the changes introduced in PR [#5106](https://github.com/brainstormforce/astra/pull/5106). Even after removing those changes which we did in the previous PR, the issue persisted. 

However, we are happy to inform you that we have successfully resolved the problem.

Once again, we appreciate your feedback and your patience throughout this process.  If you need anything else we can help you with, please don’t hesitate to [open a new ticket](https://wpastra.com/support/open-a-ticket/).

**Comment by SuperHanss** [comment]
Great! Thank you @yssambare12
