### ISSUE TITLE
After updating Astra theme to latest version site went down!

### ISSUE THREAD

**Issue by vaguemind** [brainstormforce/astra#5145]
### Describe the bug:
After upgrading Astra theme from version 3.9.4 to version 4.1.4 the website became very slow and went down! 
i checked my hosting server i found out after upgrading the theme there is a huge consuming resources to the highest so the server goes down ,, so i had to downgrade the theme again !?

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

**Comment by thebengalboy** [comment]
Hello @vaguemind 

I'm sorry to hear that you're experiencing issues with your site after updating the Astra theme. In order to assist you better, we kindly request you to open a support ticket with the Astra theme's official support channels. As the issue seems to be specific to your site's environment, it would be best to provide more details privately rather than discussing them in a public forum like this.

Thanks
