### ISSUE TITLE
Sale notification bubble goes outside of container box

### ISSUE THREAD

**Issue by aimtsou** [brainstormforce/astra#5171]
### Describe the bug:
The sale notification gets out of the container in

1. the product page in the top left corner
2. in the main page of the wordpress site where products are loaded
3. in the related products of woocommerce plugin

All this have the same problem of the sale notification going outside of the container/tile/

1) While being inside the product page the sale notification bubble goes to the top left. Although it goes outside of the container.
The affected css style:

`.woocommerce.single-product .sale:not(.ast-product-gallery-layout-vertical-slider) > span.onsale {
	 top: -.5em; 
}`

By removing the top: -.5em we get the bubble inside the container. The css flle affected is: ./themes/astra/assets/css/minified/compatibility/woocommerce/woocommerce.min.css?ver=4.1.2

2) The same happens if you have some products on the main page:
`.woocommerce ul.products li.product .onsale {
	top: 0;
	right: 0;
	left: auto;
	margin: -.5em -.5em 0 0; 
}`

Again the margin affects negatively the bubble as it leads it outside of the container. Removing margin fixes the things. The css affected is an inline one, not sure how to tackle it.

3) In the related products plugin we see products below. There we have 2 problems
Again the sale notification goes outside on the top but also it gets outside from the right on the rightmost product.

The css is: 
`.woocommerce ul.products li.product .onsale {
	top: 0;
	right: 0;
	left: auto;
	margin: -.5em -.5em 0 0;
}`

I can solve the top problem with the margin but I cannot solve the right most part.

I checked the latest version of the css file and the classes are there.

### To reproduce:
1. Go to Customize theme
2. Click on Woocommerce
3. Enable Sale notifications in the design tab

### Expected behavior
Sale bubble should be inside the container.

### Screenshots:
Case 1: https://pasteboard.co/Ns5jA4yBUp4u.png
Case 3: https://pasteboard.co/TExJcXp22Lsk.png

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2.2

### Astra Theme version:
4.1.4

**Comment by yssambare12** [comment]
Hi @aimtsou 

Thank you for reporting the issue with the sale notification positioning. I would like to inform you that the positioning of the sale notification outside of the container is actually intentional and part of the design choice. 

We have deliberately placed the sale badge in the top corner of the container to highlight the discounted products and make them more visually appealing. This design decision ensures that the sale notification stands out and catches the attention of your website visitors. 

Therefore, there is no need to worry as it is not a bug but rather a deliberate design element. 

If you need anything else we can help you with, please don’t hesitate to [[open a new ticket](https://wpastra.com/support/open-a-ticket/)]
