### ISSUE TITLE
Load Google Fonts Locally works only for a single domain

### ISSUE THREAD

**Issue by bgmastermind** [brainstormforce/astra#5291]
### Describe the bug:
When using polylang for multi languages and when using multiple domains for the different languages example.com for English and example.de for German the astra-local-fonts.css is generated with paths leading to the domain that first loaded the site. Which leads to CORS error for all subsequent page loads of the other domain.

### To reproduce:
Install polylang and add at least 2 languages with the setting for different domains.
Enable Load Google Fonts Locally in Astra settings.
Load any of the two domains.
Now switch the language (or domain) and check browser console for the CORS ERROR.

### Expected behavior:
no error

 I guess the most simple fix would be relative paths in the CSS file, but full path is used probably for a reason.

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2.2

### Astra Theme version:
4.1.7

**Comment by gebsl** [comment]
Can confirm this bug. For me it even happens without having a translator plugin active. I run a Wordpress multisite installation and Astra local fonts messes up with the URLs inside astra-local-fonts.css each time you save settings in Customizer.

There is always exactly one site in my multisite environment where local fonts work, while all other sites will face CORS errors.

Brainstormforce is well aware of this bug. I've submitted a support ticket through their internal support ticket system 1,5 years ago but they have still not come up with a solution to it, though I was reaching out to them several times.

It seems they are using webfont-loader and have even opened an issue there. However without any result so far: https://github.com/WPTT/webfont-loader/issues/16

**Comment by garvits-bsf** [comment]
Hello @bgmastermind, @gebsl,

Thank you for reporting and confirming the issue with the fonts in the multisite WordPress setup. We appreciate your suggestions and effort, and we want to inform you that we have fixed the issue after thoroughly testing it.

During the testing process, we encountered various scenarios to ensure the effectiveness of the solution. As a result, it took us some time to address the issue. We apologize for any inconvenience this may have caused you.

We will be releasing the fix for this issue in the upcoming release of Astra soon. We appreciate your feedback and your patience throughout this process. If you need any further assistance, please don’t hesitate to open a new ticket using this link: https://wpastra.com/support/open-a-ticket/.

You can find the fix PR at https://github.com/brainstormforce/astra/pull/5625.

Thank you once again for bringing this issue to our attention.

**Comment by xianglinkong** [comment]
When will the version with this fix be released? The issue still exist in the current latest version.
