### ISSUE TITLE
Upgrade to pro messages:

### ISSUE THREAD

**Issue by sakinshrestha** [brainstormforce/astra#766]
* Even after adding Astra Pro Plugin, I am still getting Pro Features and upgrade to pro message on customizer and on admin page
* Do I need to do something after installing the plugin?

**Comment by Nikschavan** [comment]
All the upgrade to pro messages should be removed after the pro addon is installed and activated, there is no other step required.

After the pro addon is installed only one notice is displayed on `plugins.php` that is for license key activation. It should not display any other notices.

![image](https://user-images.githubusercontent.com/2931091/44526063-789a0b00-a700-11e8-913c-90fdda0fcf23.png)

Can you give a screenshot of any upgrade message so that I can check that particular case?

**Comment by justintadlock** [comment]
The only thing I'm seeing is the admin notice to activate the add-on plugin once Astra Pro is installed:

> Please activate your copy of the Astra Pro to get update notifications, access to support features & other resources!

I'm not seeing any other messages.

**Comment by justintadlock** [comment]
@sakinshrestha - In that second image, try clicking the "eye" icon.  They shouldn't be disabled.  You just have to turn them on by clicking that icon.

I was a bit confused about what was happening too: https://github.com/brainstormforce/astra/issues/771

**Comment by thebengalboy** [comment]
The problem has already been resolved, but for some reason, the GitHub issue remained open. We will now close it.

If you encounter a similar issue, please don't hesitate to open a new one.
